teleop:
  base:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: /cmd_vel
    axis_mappings:
      -
        axis: 7
        target: linear.x
        scale: 0.5      
      -
        axis: 6
        target: angular.z
        scale: 0.5
      