controller_list:
  - name: fake_hexapod_arm_controller
    type: $(arg execution_type)
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
initial:  # Define initial robot poses.
  - group: hexapod_arm
    pose: folded