# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: hexapod_arm
  joint_model_group_pose: folded
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

hexapod_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gains:
    arm_joint_1:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_2:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_3:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_4:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1
    arm_joint_5:
      p: 1000
      d: 1
      i: 1
      i_clamp: 1

controller_list:
  - name: hexapod_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5