joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5

  gains:
    arm_joint_1: {p: 1000, i: 0, d: 0}
    arm_joint_2: {p: 1000, i: 0, d: 0}
    arm_joint_3: {p: 1000, i: 0, d: 0}
    arm_joint_4: {p: 1000, i: 0, d: 0}
    arm_joint_5: {p: 1000, i: 0, d: 0}

  state_publish_rate: 25

