# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: Folded
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
    # - coxa_joint_lf
    # - thigh_joint_lf
    # - tibia_joint_lf
    # - coxa_joint_lm
    # - thigh_joint_lm
    # - tibia_joint_lm
    # - coxa_joint_lr
    # - thigh_joint_lr
    # - tibia_joint_lr
    # - coxa_joint_rf
    # - thigh_joint_rf
    # - tibia_joint_rf
    # - coxa_joint_rm
    # - thigh_joint_rm
    # - tibia_joint_rm
    # - coxa_joint_rr
    # - thigh_joint_rr
    # - tibia_joint_rr
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4
    - arm_joint_5
  gains:
    arm_joint_1: { p: 1000, i: 0.0, d: 0.0, i_clamp: 1}
    arm_joint_2: { p: 1000, i: 0.0, d: 0.0, i_clamp: 1}
    arm_joint_3: { p: 1000, i: 0.0, d: 0.0, i_clamp: 1}
    arm_joint_4: { p: 1000, i: 0.0, d: 0.0, i_clamp: 1}
    arm_joint_5: { p: 1000, i: 0.0, d: 0.0, i_clamp: 1}
  
  state_publish_rate: 25


controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5