joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

hexapod_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
    - coxa_joint_lf
    - femur_joint_lf
    - tibia_joint_lf
    - coxa_joint_lm
    - femur_joint_lm
    - tibia_joint_lm
    - coxa_joint_lr
    - femur_joint_lr
    - tibia_joint_lr
    - coxa_joint_rf
    - femur_joint_rf
    - tibia_joint_rf
    - coxa_joint_rm
    - femur_joint_rm
    - tibia_joint_rm
    - coxa_joint_rr
    - femur_joint_rr
    - tibia_joint_rr

  coxa_joint_lf:
    pid: {p: 100, i: 20, d: 1.0}
  femur_joint_lf:
    pid: {p: 100, i: 20, d: 1.0}
  tibia_joint_lf:
    pid: {p: 100, i: 20, d: 1.0}
  coxa_joint_lm:
    pid: {p: 100, i: 20, d: 1.0}
  femur_joint_lm:
    pid: {p: 100, i: 20, d: 1.0}
  tibia_joint_lm:
    pid: {p: 100, i: 20, d: 1.0}
  coxa_joint_lr:
    pid: {p: 100, i: 20, d: 1.0}
  femur_joint_lr:
    pid: {p: 100, i: 20, d: 1.0}
  tibia_joint_lr:
    pid: {p: 100, i: 20, d: 1.0}
  coxa_joint_rf:
    pid: {p: 100, i: 20, d: 1.0}
  femur_joint_rf:
    pid: {p: 100, i: 20, d: 1.0}
  tibia_joint_rf:
    pid: {p: 100, i: 20, d: 1.0}  
  coxa_joint_rm:
    pid: {p: 100, i: 20, d: 1.0}
  femur_joint_rm:
    pid: {p: 100, i: 20, d: 1.0}
  tibia_joint_rm:
    pid: {p: 100, i: 20, d: 1.0}
  coxa_joint_rr:
    pid: {p: 100, i: 20, d: 1.0}
  femur_joint_rr:
    pid: {p: 100, i: 20, d: 1.0}
  tibia_joint_rr:
    pid: {p: 100, i: 20, d: 1.0}
